package model

import (
	"strings"
	"time"
)

// Sender represents the originator of a conversation message.
type Sender string

const (
	// SenderCustomer represents messages sent by the customer.
	SenderCustomer Sender = "CUSTOMER"

	// SenderAgent represents messages sent by the AI/agent.
	SenderAgent Sender = "AGENT"

	// SenderSystem represents messages generated by system events.
	SenderSystem Sender = "SYSTEM"
)

// Message represents an immutable conversational message value object.
type Message struct {
	id        string
	sender    Sender
	content   string
	timestamp time.Time
}

// NewMessage creates and validates a new Message value object.
func NewMessage(id string, sender Sender, content string, timestamp time.Time) (Message, error) {
	trimmed := strings.TrimSpace(content)
	if trimmed == "" {
		return Message{}, ErrInvalidMessage
	}
	if timestamp.IsZero() {
		timestamp = time.Now().UTC()
	}
	return Message{
		id:        id,
		sender:    sender,
		content:   trimmed,
		timestamp: timestamp,
	}, nil
}

// ID returns the message identifier.
func (m Message) ID() string {
	return m.id
}

// Sender returns the sender role.
func (m Message) Sender() Sender {
	return m.sender
}

// Content returns the textual message content.
func (m Message) Content() string {
	return m.content
}

// Timestamp returns the time the message was created.
func (m Message) Timestamp() time.Time {
	return m.timestamp
}
